Repository medhost/fhir-works-on-aws-deployment, pull requests merged in 2021-02, with the labels that each got.

#21 Mainline multitenancy sync.
  .github/workflows/labeler.yml
  DEVELOPMENT.md
  auditLogMover/package.json
  auditLogMover/yarn.lock
  cloudformation/kms.yaml
  package.json
  serverless.yaml
  yarn.lock
Labels: size/xl

#22 dependency version update.
  package.json
  yarn.lock
Labels: size/s

#23 Multitenancy develop sync.
  .github/workflows/labeler.yml
  DEVELOPMENT.md
  auditLogMover/package.json
  auditLogMover/yarn.lock
  cloudformation/kms.yaml
  package.json
  serverless.yaml
  yarn.lock
Labels: size/xl

#26 [YCU-47939] setting up s3 config
  cloudformation/bulkExport.yaml
  serverless.yaml
Labels: size/s

#28 Add Global Secondary Index
  serverless.yaml
Labels: size/s

#29 [YCU-47940] Setup elasticsearch. Added serverless diff plugin for ci/…
  cloudformation/bulkExport.yaml
  cloudformation/elasticsearch.yaml
  package.json
  serverless.yaml
Labels: size/s

#30 Remove Attributes
  serverless.yaml
Labels: size/xs
