Repository medhost/fhir-works-on-aws-deployment, pull requests merged in 2021-04, with the labels that each got.

#37 merge infra changes from medhost-develop w/medhost-develop-smart
  cloudformation/bulkExport.yaml
  cloudformation/elasticsearch.yaml
  package.json
  serverless.yaml
Labels: size/m

#40 [YCU-47949] fixing indent issue
  serverless.yaml
Labels: size/xs

#41 Mainline multitenancy sync
  package.json
  serverless.yaml
  yarn.lock
Labels: size/s

#42 re adding lambda permissions lost in merge
  serverless.yaml
Labels: size/s

#43 Yaml cleanup.
  serverless.yaml
Labels: size/xs

#44 [YCU-47950] Enabling acceleration on binary s3 bucket
  serverless.yaml
Labels: size/xs
