Repository medhost/fhir-works-on-aws-deployment, pull requests merged in 2021-03, with the labels that each got.

#31 Feature/ycu 47928 setup private api gateway
  serverless.yaml
Labels: size/xs

#32 Changing !Sub to !Join for local develop issue
  serverless.yaml
Labels: size/xs

#27 multitenancy: add tenantId to export script
  bulkExport/glueScripts/export-script.py
Labels: size/xs

#33 Sync multitenancy from mainline 03.16
  .github/workflows/deploy.yaml
  CODE_OF_CONDUCT.md
  CUSTOMIZE.md
  DEVELOPMENT.md
  INSTALL.md
  README.md
  THIRD-PARTY
  auditLogMover/package.json
  auditLogMover/serverless.yaml
  auditLogMover/tsconfig.json
  auditLogMover/yarn.lock
  integration-tests/bulkExport.test.ts
  integration-tests/rbac-permission.test.ts
  integration-tests/utils.ts
  package.json
  resources/architecture.png
  scripts/fhir-works-deploy.sh
  scripts/win_install.ps1
  serverless.yaml
  src/config.ts
  tsconfig.json
  yarn.lock
Labels: size/xl

#34 Feature/ycu 48041 tenants segregated by ddb tables
  cloudformation/dynamodbScaling.yaml
  serverless.yaml
Labels: size/m

#36 Add additional attributes needed for GSI.
  serverless.yaml
Labels: size/xs

#35 Cleanup/decoupling terraform related policies from serverless
  serverless.yaml
Labels: size/s
